import Head from 'next/head'
import Header from './components/Header.js';
import Footer from './components/Footer.js';
import CookieStandForm from './components/CookieStandForm.js';
import ReportTable from './components/ReportTable.js';
import useResource from '@/hooks/useResource.js';
// import { useAuth } from '@/contexts/auth.js';

export default function Home() {
  const {resources} = useResource();

  return (
    <>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <main className='font-serif'>
        <CookieStandForm />
        <ReportTable cookieStands={resources || []} />
        <Footer cookieStands={resources} />
      </main>
    </>
  )
}
